name: Deploy to AWS VM

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_VM_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo "Successfully connected to AWS VM!"
            sudo apt-get update -y
            sudo apt-get install nginx -y
            echo "<h1>Hello from GitHub Actions Automation!</h1>" | sudo tee /var/www/html/index.html
            sudo systemctl restart nginx
